modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
    modId="frozenup"
    version="${file.jarVersion}"

    displayName="Frozen Up"
    description="Frozen Up is a small mod that adds a bunch of new snowy features while keeping in mind the classic minecraft feel."
    logoFile="pack.png"

    displayURL="https://frozenup.teamdraco.net"
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional

    credits="[CODE] Coda, superlord9362, andante. [ART] Ninni"
    authors="Team Draco"

[[dependencies.frozenup]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.frozenup]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
